In [4]:
#!pip install kaggle
import kaggle
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [21]:
#Extract file from zip file 
import zipfile
zip_ref = zipfile.ZipFile("orders.csv.zip")
zip_ref.extractall() # extract file to dir
zip_ref.close() # close file

In [23]:
import pandas as pd
df = pd.read_csv("orders.csv")

In [25]:
df.head(10)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3

In [27]:
# check the different types of null values in coln "Ship Mode"
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [29]:
# we have "Not available", "unknown", nan this representing the null values nan is representing null
# so we convert Not Available, Unkonwn into null values or nan
df = pd.read_csv("orders.csv",na_values = ['Not Available', 'unknown'])
# na_values change it to null values

In [31]:
df.head(10)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3

In [33]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [35]:
# rename columns name : make it lowercase and remove space between 2 words and replace it with underscore _
df.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='object')

In [37]:
df.columns=df.columns.str.lower()

In [39]:
df.columns

Index(['order id', 'order date', 'ship mode', 'segment', 'country', 'city',
       'state', 'postal code', 'region', 'category', 'sub category',
       'product id', 'cost price', 'list price', 'quantity',
       'discount percent'],
      dtype='object')

In [41]:
#replacing space by underscore _
df.columns = df.columns.str.replace(" ","_")

In [43]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [45]:
# creating discount column 
df['discount']=df["list_price"]*df["discount_percent"]*0.01 # 0.01 = 100
# sale price
df['sale_price']=df['list_price'] - df['discount']
# profit
df["profit"] = df['sale_price'] - df['cost_price']
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [47]:
# check the data types 
df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sale_price          float64
profit              float64
dtype: object

In [49]:
# change the data type of order_date to datetime
#pd.to_datetime(df['order_date'],format = "%Y-%m-d")
df['order_date'] = pd.to_datetime(df['order_date'], format="%Y-%m-%d")
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [51]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [53]:
# drop unnecessary columns
df.drop(columns = ['cost_price'	,'list_price','discount_percent'],inplace = True)

In [55]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [61]:
!pip install pymysql

Collecting pymysql
  Obtaining dependency information for pymysql from https://files.pythonhosted.org/packages/0c/94/e4181a1f6286f545507528c78016e00065ea913276888db2262507693ce5/PyMySQL-1.1.1-py3-none-any.whl.metadata
  Using cached PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Using cached PyMySQL-1.1.1-py3-none-any.whl (44 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [63]:
#import pymysql

In [71]:
# mysql localhost password 12345
##dbcon = pymysql.connect(host = 'localhost',user = 'root',password = '12345',database = "orders")

In [73]:
#dbcon not important

## Transfering the data to mysql

In [75]:
from sqlalchemy import create_engine

In [79]:
username = 'root'
password = '12345'
host = 'localhost'
database = 'orders'
connection_string = f'mysql+mysqlconnector://{username}:{password}@{host}/{database}'

In [86]:
pip install mysql-connector-python

Collecting mysql-connector-pythonNote: you may need to restart the kernel to use updated packages.

  Obtaining dependency information for mysql-connector-python from https://files.pythonhosted.org/packages/5f/c3/b4c36fbc65c119fca83f258557573d8cd296da5e198d3752c669f8e871e2/mysql_connector_python-9.0.0-cp311-cp311-win_amd64.whl.metadata
  Downloading mysql_connector_python-9.0.0-cp311-cp311-win_amd64.whl.metadata (2.0 kB)
Downloading mysql_connector_python-9.0.0-cp311-cp311-win_amd64.whl (14.3 MB)
   ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.3 MB 262.6 kB/s eta 0:00:55
   ---------------------------------------- 0.1/14.3 MB 327.7 kB/s eta 0:00:44
   ---------------------------------------- 0.1/14.3 MB 492.8 kB/s eta 0:00:29
   ---------------------------------------- 0.2/14.3 MB 612.6 kB/s eta 0:00:24
    --------------------------------------- 0.2/14.3 MB 731.4 kB/s eta 0:00:20
    --------------------------------------- 0.3/14.3 MB 787.7 kB/s eta 0:00:18
    --------------------------------------- 0.3/14.3 MB 952.6 kB/s eta 0:00:15
   - -------------------------------------- 0.4/14.3 MB 995.2 kB/s eta 0:00:15
   - -------------------------------------- 0.5/14.3 MB 1.2 MB/s eta 0:00:12
   - -------------------------------------- 0.6/14.3 MB 1.2 MB/s eta 0:00:12
   - -------------------------------------- 0.7/14.3 MB 1.3 MB/s eta 0:00:11
   -- ------------------------------------- 0.7/14.3 MB 1.3 MB/s eta 0:00:11
   -- ------------------------------------- 0.7/14.3 MB 1.3 MB/s eta 0:00:11
   -- ------------------------------------- 0.9/14.3 MB 1.1 MB/s eta 0:00:13
   -- ------------------------------------- 1.0/14.3 MB 1.1 MB/s eta 0:00:12
   --- ------------------------------------ 1.2/14.3 MB 1.2 MB/s eta 0:00:11
   --- ------------------------------------ 1.2/14.3 MB 1.2 MB/s eta 0:00:11
   --- ------------------------------------ 1.4/14.3 MB 1.3 MB/s eta 0:00:11
   ---- ----------------------------------- 1.4/14.3 MB 1.3 MB/s eta 0:00:10
   ---- ----------------------------------- 1.6/14.3 MB 1.3 MB/s eta 0:00:10
   ---- ----------------------------------- 1.6/14.3 MB 1.3 MB/s eta 0:00:10
   ---- ----------------------------------- 1.8/14.3 MB 1.4 MB/s eta 0:00:10
   ----- ---------------------------------- 1.9/14.3 MB 1.4 MB/s eta 0:00:09
   ----- ---------------------------------- 2.0/14.3 MB 1.5 MB/s eta 0:00:09
   ----- ---------------------------------- 2.1/14.3 MB 1.5 MB/s eta 0:00:09
   ------ --------------------------------- 2.2/14.3 MB 1.5 MB/s eta 0:00:09
   ------ --------------------------------- 2.3/14.3 MB 1.5 MB/s eta 0:00:08
   ------ --------------------------------- 2.5/14.3 MB 1.6 MB/s eta 0:00:08
   ------- -------------------------------- 2.6/14.3 MB 1.6 MB/s eta 0:00:08
   ------- -------------------------------- 2.7/14.3 MB 1.6 MB/s eta 0:00:08
   ------- -------------------------------- 2.8/14.3 MB 1.6 MB/s eta 0:00:08
   -------- ------------------------------- 2.9/14.3 MB 1.7 MB/s eta 0:00:07
   -------- ------------------------------- 3.0/14.3 MB 1.7 MB/s eta 0:00:07
   -------- ------------------------------- 3.2/14.3 MB 1.7 MB/s eta 0:00:07
   --------- ------------------------------ 3.4/14.3 MB 1.7 MB/s eta 0:00:07
   --------- ------------------------------ 3.5/14.3 MB 1.7 MB/s eta 0:00:07
   ---------- ----------------------------- 3.7/14.3 MB 1.8 MB/s eta 0:00:07
   ---------- ----------------------------- 3.9/14.3 MB 1.8 MB/s eta 0:00:06
   ----------- ---------------------------- 4.0/14.3 MB 1.8 MB/s eta 0:00:06
   ----------- ---------------------------- 4.1/14.3 MB 1.8 MB/s eta 0:00:06
   ----------- ---------------------------- 4.3/14.3 MB 1.9 MB/s eta 0:00:06
   ------------ --------------------------- 4.5/14.3 MB 1.9 MB/s eta 0:00:06
   ------------ --------------------------- 4.6/14.3 MB 1.9 MB/s eta 0:00:06
   ------------- -------------------------- 4.8/14.3 MB 1.9 MB/s eta 0:00:05
   ------------- -------------------------- 4.9/14.3 MB 1.9 MB/s eta 0:00:05
   -------------- ------------------------- 5.1/14.3 MB 2.0 MB/s eta 0:00:05
   --------------- ------------------------ 5.4/14.3 MB 1.9 MB/s eta 0:00:05
   --------------- ------------------------ 5.6/14.3 MB 1.9 MB/s eta 0:00:05
   --------------- ------------------------ 5.6/14.3 MB 1.9 MB/s eta 0:00:05
   --------------- ------------------------ 5.6/14.3 MB 1.9 MB/s eta 0:00:05
   --------------- ------------------------ 5.6/14.3 MB 1.9 MB/s eta 0:00:05
   ---------------- ----------------------- 5.8/14.3 MB 1.9 MB/s eta 0:00:05
   ---------------- ----------------------- 5.8/14.3 MB 1.9 MB/s eta 0:00:05
   ---------------- ----------------------- 5.9/14.3 MB 1.9 MB/s eta 0:00:05
   ---------------- ----------------------- 6.0/14.3 MB 1.9 MB/s eta 0:00:05
   ---------------- ----------------------- 6.1/14.3 MB 1.9 MB/s eta 0:00:05
   ----------------- ---------------------- 6.2/14.3 MB 1.9 MB/s eta 0:00:05
   ----------------- ---------------------- 6.3/14.3 MB 1.9 MB/s eta 0:00:05
   ----------------- ---------------------- 6.4/14.3 MB 1.9 MB/s eta 0:00:05
   ------------------ --------------------- 6.6/14.3 MB 1.9 MB/s eta 0:00:05
   ------------------ --------------------- 6.6/14.3 MB 1.9 MB/s eta 0:00:05
   ------------------ --------------------- 6.7/14.3 MB 1.9 MB/s eta 0:00:05
   ------------------- -------------------- 7.1/14.3 MB 1.9 MB/s eta 0:00:04
   ------------------- -------------------- 7.1/14.3 MB 1.8 MB/s eta 0:00:04
   ------------------- -------------------- 7.1/14.3 MB 1.8 MB/s eta 0:00:04
   -------------------- ------------------- 7.3/14.3 MB 1.8 MB/s eta 0:00:04
   -------------------- ------------------- 7.4/14.3 MB 1.8 MB/s eta 0:00:04
   -------------------- ------------------- 7.4/14.3 MB 1.8 MB/s eta 0:00:04
   -------------------- ------------------- 7.5/14.3 MB 1.8 MB/s eta 0:00:04
   --------------------- ------------------ 7.5/14.3 MB 1.8 MB/s eta 0:00:04
   --------------------- ------------------ 7.7/14.3 MB 1.8 MB/s eta 0:00:04
   --------------------- ------------------ 7.7/14.3 MB 1.8 MB/s eta 0:00:04
   --------------------- ------------------ 7.8/14.3 MB 1.8 MB/s eta 0:00:04
   --------------------- ------------------ 7.8/14.3 MB 1.8 MB/s eta 0:00:04
   ---------------------- ----------------- 7.9/14.3 MB 1.8 MB/s eta 0:00:04
   ---------------------- ----------------- 7.9/14.3 MB 1.8 MB/s eta 0:00:04
   ---------------------- ----------------- 8.0/14.3 MB 1.8 MB/s eta 0:00:04
   ---------------------- ----------------- 8.0/14.3 MB 1.7 MB/s eta 0:00:04
   ---------------------- ----------------- 8.1/14.3 MB 1.7 MB/s eta 0:00:04
   ---------------------- ----------------- 8.2/14.3 MB 1.7 MB/s eta 0:00:04
   ----------------------- ---------------- 8.3/14.3 MB 1.7 MB/s eta 0:00:04
   ----------------------- ---------------- 8.4/14.3 MB 1.7 MB/s eta 0:00:04
   ----------------------- ---------------- 8.4/14.3 MB 1.7 MB/s eta 0:00:04
   ----------------------- ---------------- 8.5/14.3 MB 1.7 MB/s eta 0:00:04
   ------------------------ --------------- 8.7/14.3 MB 1.7 MB/s eta 0:00:04
   ------------------------ --------------- 8.7/14.3 MB 1.7 MB/s eta 0:00:04
   ------------------------ --------------- 8.8/14.3 MB 1.7 MB/s eta 0:00:04
   ------------------------ --------------- 8.9/14.3 MB 1.7 MB/s eta 0:00:04
   ------------------------- -------------- 9.0/14.3 MB 1.7 MB/s eta 0:00:04
   ------------------------- -------------- 9.1/14.3 MB 1.7 MB/s eta 0:00:04
   ------------------------- -------------- 9.2/14.3 MB 1.7 MB/s eta 0:00:04
   ------------------------- -------------- 9.3/14.3 MB 1.7 MB/s eta 0:00:03
   -------------------------- ------------- 9.5/14.3 MB 1.7 MB/s eta 0:00:03
   -------------------------- ------------- 9.6/14.3 MB 1.7 MB/s eta 0:00:03
   --------------------------- ------------ 9.7/14.3 MB 1.7 MB/s eta 0:00:03
   --------------------------- ------------ 9.8/14.3 MB 1.7 MB/s eta 0:00:03
   --------------------------- ------------ 10.0/14.3 MB 1.7 MB/s eta 0:00:03
   ---------------------------- ----------- 10.1/14.3 MB 1.7 MB/s eta 0:00:03
   ---------------------------- ----------- 10.3/14.3 MB 1.8 MB/s eta 0:00:03
   ----------------------------- ---------- 10.4/14.3 MB 1.8 MB/s eta 0:00:03
   ----------------------------- ---------- 10.5/14.3 MB 1.8 MB/s eta 0:00:03
   ----------------------------- ---------- 10.7/14.3 MB 1.8 MB/s eta 0:00:03
   ------------------------------ --------- 10.8/14.3 MB 1.8 MB/s eta 0:00:02
   ------------------------------ --------- 11.0/14.3 MB 1.9 MB/s eta 0:00:02
   ------------------------------- -------- 11.2/14.3 MB 1.9 MB/s eta 0:00:02
   ------------------------------- -------- 11.3/14.3 MB 1.9 MB/s eta 0:00:02
   ------------------------------- -------- 11.4/14.3 MB 1.9 MB/s eta 0:00:02
   -------------------------------- ------- 11.6/14.3 MB 1.9 MB/s eta 0:00:02
   -------------------------------- ------- 11.7/14.3 MB 1.9 MB/s eta 0:00:02
   --------------------------------- ------ 11.9/14.3 MB 1.9 MB/s eta 0:00:02
   --------------------------------- ------ 12.0/14.3 MB 2.0 MB/s eta 0:00:02
   --------------------------------- ------ 12.2/14.3 MB 2.0 MB/s eta 0:00:02
   ---------------------------------- ----- 12.3/14.3 MB 2.0 MB/s eta 0:00:02
   ----------------------------------- ---- 12.6/14.3 MB 2.0 MB/s eta 0:00:01
   ----------------------------------- ---- 12.7/14.3 MB 2.0 MB/s eta 0:00:01
   ----------------------------------- ---- 12.9/14.3 MB 2.0 MB/s eta 0:00:01
   ------------------------------------ --- 13.1/14.3 MB 2.0 MB/s eta 0:00:01
   ------------------------------------ --- 13.2/14.3 MB 2.0 MB/s eta 0:00:01
   ------------------------------------- -- 13.5/14.3 MB 2.0 MB/s eta 0:00:01
   ------------------------------------- -- 13.6/14.3 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 13.8/14.3 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 14.0/14.3 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  14.0/14.3 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  14.3/14.3 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  14.3/14.3 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 14.3/14.3 MB 2.0 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.0.0

In [90]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\dell\anaconda3\lib\site-packages (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [96]:
engine = create_engine(connection_string)

# Transfer data to MySQL
#df.to_sql(name='df', con=engine, if_exists='replace', index=False)
# or
df.to_sql(name = 'orders',con = engine,if_exists = 'append',index = False)

9994

In [94]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8